# Generated by Django 5.0.4 on 2024-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('sdob', models.DateField()),
                ('semail', models.EmailField(max_length=254)),
                ('saddr', models.TextField()),
                ('sphone', models.CharField(max_length=30)),
            ],
        ),
    ]
